import type { Campaign, JournalPost } from "@/lib/types";

export const demoCampaigns: Campaign[] = [
  {
    id: "camp-three-friends",
    slug: "three-friends",
    name: "The Three Friends",
    eyebrow: "An ongoing campaign",
    tagline: "Every friendship deserves a witness.",
    summary:
      "A shared chronicle of narrow escapes, hard-won allies, dangerous relics, and the roads still waiting beyond the firelight.",
    coverUrl: "/og.png",
    accent: "oxblood",
    publishedPostCount: 3,
    updatedAt: "2026-07-19T18:30:00.000Z",
  },
  {
    id: "camp-tomb",
    slug: "tomb-of-annihilation",
    name: "Tomb of Annihilation",
    eyebrow: "Expedition journal",
    tagline: "The jungle remembers every footstep.",
    summary:
      "Field notes, recovered artifacts, and the faces encountered on a long road through Chult.",
    coverUrl: null,
    accent: "forest",
    publishedPostCount: 1,
    updatedAt: "2026-06-28T21:00:00.000Z",
  },
];

export const demoPosts: JournalPost[] = [
  {
    id: "post-session-14",
    campaignId: "camp-three-friends",
    campaignSlug: "three-friends",
    campaignName: "The Three Friends",
    kind: "session",
    status: "published",
    title: "Session XIV — The Ruins Answer Back",
    body:
      "The road ended at a keep no map admitted was there. By dusk, the party had crossed its fallen gate, bargained with a voice in the well, and learned why every bird in the valley went silent at sundown.\n\nThey left with one promise made, one door deliberately unopened, and the uneasy certainty that something beneath the keep now knows their names.",
    eventDate: "2026-07-18",
    displayOrder: 3072,
    pinned: false,
    source: "tracker",
    sourceRef: "sample-session-14",
    media: [
      {
        id: "media-ruins",
        postId: "post-session-14",
        objectKey: "demo/ruins",
        url: "/og.png",
        altText: "A parchment map beside a distant ruined keep",
        caption: "The keep at the end of the unmarked road.",
        displayOrder: 0,
      },
    ],
    publishedAt: "2026-07-19T18:30:00.000Z",
    archivedAt: null,
    createdAt: "2026-07-19T18:00:00.000Z",
    updatedAt: "2026-07-19T18:30:00.000Z",
  },
  {
    id: "post-captain-vael",
    campaignId: "camp-three-friends",
    campaignSlug: "three-friends",
    campaignName: "The Three Friends",
    kind: "npc",
    status: "published",
    title: "Captain Vael",
    body:
      "Commander of the eastern watch and a reluctant keeper of old promises. Vael speaks plainly, notices everything, and never removes the weathered silver ring tied around his sword belt.",
    eventDate: "2026-07-11",
    displayOrder: 2048,
    pinned: false,
    source: "maker",
    sourceRef: "sample-npc-vael",
    media: [],
    publishedAt: "2026-07-12T16:00:00.000Z",
    archivedAt: null,
    createdAt: "2026-07-12T15:50:00.000Z",
    updatedAt: "2026-07-12T16:00:00.000Z",
  },
  {
    id: "post-moonlit-key",
    campaignId: "camp-three-friends",
    campaignSlug: "three-friends",
    campaignName: "The Three Friends",
    kind: "item",
    status: "published",
    title: "The Moonlit Key",
    body:
      "A narrow iron key whose teeth cast a different shadow under moonlight. It was recovered wrapped in blue thread with a note: “For the door that has forgotten it is a door.”",
    eventDate: "2026-07-04",
    displayOrder: 1024,
    pinned: false,
    source: "maker",
    sourceRef: "sample-item-key",
    media: [],
    publishedAt: "2026-07-05T17:15:00.000Z",
    archivedAt: null,
    createdAt: "2026-07-05T17:00:00.000Z",
    updatedAt: "2026-07-05T17:15:00.000Z",
  },
  {
    id: "post-draft-wayfinder",
    campaignId: "camp-three-friends",
    campaignSlug: "three-friends",
    campaignName: "The Three Friends",
    kind: "lore",
    status: "draft",
    title: "The Wayfinder’s Warning",
    body:
      "A player-safe fragment is ready to review. Add a little context, choose the date it was discovered, and publish when it feels right.",
    eventDate: "2026-07-24",
    displayOrder: 4096,
    pinned: false,
    source: "maker",
    sourceRef: "sample-lore-wayfinder",
    media: [],
    publishedAt: null,
    archivedAt: null,
    createdAt: "2026-07-24T20:00:00.000Z",
    updatedAt: "2026-07-24T20:00:00.000Z",
  },
  {
    id: "post-tomb-session",
    campaignId: "camp-tomb",
    campaignSlug: "tomb-of-annihilation",
    campaignName: "Tomb of Annihilation",
    kind: "session",
    status: "published",
    title: "Field Note — Rain Over the River",
    body:
      "Three days of hard rain turned every trail into a stream. The expedition found higher ground, an abandoned signal fire, and fresh tracks belonging to something that walked on two feet until it did not.",
    eventDate: "2026-06-27",
    displayOrder: 1024,
    pinned: false,
    source: "tracker",
    sourceRef: "sample-tomb-session",
    media: [],
    publishedAt: "2026-06-28T21:00:00.000Z",
    archivedAt: null,
    createdAt: "2026-06-28T20:45:00.000Z",
    updatedAt: "2026-06-28T21:00:00.000Z",
  },
];
